name: qa-clean-dev
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - openpyxl>=3.1.0
  - scikit-learn>=1.1.0
  - numpy>=1.21.0
  - tqdm>=4.64.0
  - jieba>=0.42.1
  - pip
  - pip:
    - sentence-transformers>=2.2.0
    - torch>=1.13.0
    - faiss-gpu>=1.7.2
    - psycopg2-binary>=2.9.9
    - ruff>=0.5
    - mypy>=1.8
    - pytest>=8
    - types-tqdm
    - pandas-stubs
